/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//todo: this is temporary for demo purposes

import { useAnimations, useGLTF } from "@react-three/drei";
import { useEffect, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import animationGLB from "../../../../assets/3d/idle.glb?url";
import avatarGLB from "../../../../assets/3d/me.glb?url";

type GLTFResult = GLTF & {
	nodes: {
		Wolf3D_Avatar: THREE.SkinnedMesh;
		Hips: THREE.Bone;
	};
	materials: {
		Wolf3D_Avatar: THREE.MeshStandardMaterial;
	};
};

export default function AvatarModel() {
	const avatar = useRef(undefined);
	const { nodes, materials } = useGLTF(avatarGLB) as unknown as GLTFResult;
	const { animations } = useGLTF(animationGLB) as unknown as GLTFResult;
	const { actions } = useAnimations(animations, avatar);

	console.log("actions", actions);
	console.log(actions["Armature|mixamo.com|Layer0.001"]);

	useEffect(() => {
		actions["Armature|mixamo.com|Layer0.001"]?.play();
	});

	return (
		<group dispose={null}>
			<primitive object={nodes.Hips} ref={avatar} />
			<skinnedMesh
				name="Wolf3D_Avatar"
				geometry={nodes.Wolf3D_Avatar.geometry}
				material={materials.Wolf3D_Avatar}
				skeleton={nodes.Wolf3D_Avatar.skeleton}
				morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary}
				morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences}
			/>
		</group>
	);
}

useGLTF.preload(avatarGLB);
useGLTF.preload(animationGLB);
